version: "3"

services:
  web:
    image: torqbit/torq:0.1.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:torq123@db.torqbit.com/torqdb
      - GOOGLE_ID=*****************
      - GOOGLE_SECRET=*************
      - GITHUB_ID=*****************
      - GITHUB_SECRET=*************
      - NEXT_PUBLIC_SECRET=d090c4d9bea3f1076d6ebc47460d0e0988a9924ddfa1e8691cbbf28e3f4638cd
      - JWT_SECRET=uPijyPl163ihk570eXbQrNMnKW4
      - NEXTAUTH_URL=http://localhost:3000
      - ADMIN_EMAIL=your@mail.com
      - NEXT_PUBLIC_APP_ENV=development
    networks:
      - app-network

  db:
    image: mysql:8.0
    hostname: db.torqbit.com
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: torq123
      MYSQL_DATABASE: torqdb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
