image:
  repository: torqbit/torqbit
  tag: 0.1.2-rc3
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: "example.local"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

containers:
  - name: torqbit
    image: torqbit/torqbit:0.1.2-rc3
    env:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: DATABASE_URL
      - name: GOOGLE_ID
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: GOOGLE_ID
      - name: GOOGLE_SECRET
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: GOOGLE_SECRET
      - name: GITHUB_ID
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: GITHUB_ID
      - name: GITHUB_SECRET
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: GITHUB_SECRET
      - name: NEXT_PUBLIC_SECRET
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: NEXT_PUBLIC_SECRET
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: JWT_SECRET
      - name: NEXTAUTH_URL
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: NEXTAUTH_URL
      - name: ADMIN_EMAIL
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: ADMIN_EMAIL
      - name: NEXT_PUBLIC_APP_ENV
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: NEXT_PUBLIC_APP_ENV
      - name: NODE_ENV
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: NODE_ENV
      - name: CASHFREE_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: CASHFREE_SECRET_KEY
      - name: CASHFREE_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: CASHFREE_CLIENT_ID
      - name: GATEWAY_PROVIDER_NAME
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: GATEWAY_PROVIDER_NAME
      - name: NEXT_SMTP_HOST
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: NEXT_SMTP_HOST
      - name: NEXT_SMTP_USER
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: NEXT_SMTP_USER
      - name: NEXT_SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: NEXT_SMTP_PASSWORD
      - name: MEDIA_UPLOAD_PATH
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: MEDIA_UPLOAD_PATH
      - name: INVOICE_UPLOAD_PATH
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: INVOICE_UPLOAD_PATH
      - name: FROM_SMTP_USER_EMAIL
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: FROM_SMTP_USER_EMAIL
      - name: VERIFIED_EMAIL
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: VERIFIED_EMAIL
      - name: FROM_SMTP_SUPPORT_EMAIL
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: FROM_SMTP_SUPPORT_EMAIL
      - name: NEXT_PUBLIC_NEXTAUTH_URL
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: NEXT_PUBLIC_NEXTAUTH_URL
      - name: INVOICE_DIRECTORY
        valueFrom:
          secretKeyRef:
            name: torqbit-secrets
            key: INVOICE_DIRECTORY
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10; done"]
    ports:
      - containerPort: 3000

containers:
  ports:
    containerPort: 3000
autoscaling:
  enabled: false