apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "torqbit.fullname" . }}
  labels:
    app: {{ include "torqbit.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "torqbit.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "torqbit.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containers.ports.containerPort }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: DATABASE_URL
            - name: GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: GOOGLE_ID
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: GOOGLE_SECRET
            - name: GITHUB_ID
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: GITHUB_ID
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: GITHUB_SECRET
            - name: NEXT_PUBLIC_SECRET
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: NEXT_PUBLIC_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: JWT_SECRET
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: NEXTAUTH_URL
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: ADMIN_EMAIL
            - name: NEXT_PUBLIC_APP_ENV
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: NEXT_PUBLIC_APP_ENV
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: NODE_ENV
            - name: CASHFREE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: CASHFREE_SECRET_KEY
            - name: CASHFREE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: CASHFREE_CLIENT_ID
            - name: GATEWAY_PROVIDER_NAME
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: GATEWAY_PROVIDER_NAME
            - name: NEXT_SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: NEXT_SMTP_HOST
            - name: NEXT_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: NEXT_SMTP_USER
            - name: NEXT_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: NEXT_SMTP_PASSWORD
            - name: MEDIA_UPLOAD_PATH
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: MEDIA_UPLOAD_PATH
            - name: INVOICE_UPLOAD_PATH
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: INVOICE_UPLOAD_PATH
            - name: FROM_SMTP_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: FROM_SMTP_USER_EMAIL
            - name: VERIFIED_EMAIL
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: VERIFIED_EMAIL
            - name: FROM_SMTP_SUPPORT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: FROM_SMTP_SUPPORT_EMAIL
            - name: NEXT_PUBLIC_NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: NEXT_PUBLIC_NEXTAUTH_URL
            - name: INVOICE_DIRECTORY
              valueFrom:
                secretKeyRef:
                  name: torqbit-secrets
                  key: INVOICE_DIRECTORY
          args: ["sh", "-c", "npx prisma db push --accept-data-loss && yarn start"]
      restartPolicy: Always