apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "torqbit.fullname" . }}
  labels:
    app: {{ include "torqbit.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "torqbit.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "torqbit.name" . }}
    spec:
      initContainers:
      - name: wait-for-mysql
        image: mysql:8.0.12
        command:
        - sh
        - -c
        - |
          echo "Waiting for MySQL...";
          while ! mysqladmin ping -h mysql-service.default.svc.cluster.local -u $$MYSQL_USER --password=$$MYSQL_PASSWORD; do
            echo "Still waiting...";
            sleep 5;
          done;
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.containers.ports.containerPort }}
        envFrom:
        - secretRef:
            name: torqbit-secrets
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.containers.ports.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
        args: ["sh", "-c", "npx prisma db push --accept-data-loss && yarn start"]
      restartPolicy: Always
