apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
