apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: a2FsaQ== # base64 encoded value for "kali"
  MYSQL_DATABASE: a2FsaQ== # base64 encoded value for "kali"
  MYSQL_USER: a2FsaQ== # base64 encoded value for "kali"
  MYSQL_PASSWORD: a2FsaQ== # base64 encoded value for "kali"
